// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT002LoginInvlidoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT002LoginInvlido() {
    // Test name: CT002_LoginInválido
    // Step # | name | target | value
    // 1 | open | / | 
    // Acessa o Site
    driver.get("http://localhost:5173/");
    // 2 | assertElementPresent | css=b | 
    // Validação dos elementos da tela inicial
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("b"));
      assert(elements.size() > 0);
    }
    // 3 | assertElementPresent | css=.btn:nth-child(1) | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".btn:nth-child(1)"));
      assert(elements.size() > 0);
    }
    // 4 | assertElementPresent | css=.btn:nth-child(2) | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".btn:nth-child(2)"));
      assert(elements.size() > 0);
    }
    // 5 | click | css=.btn:nth-child(1) | 
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    // 6 | assertElementPresent | id=formBasicEmail | 
    // validação dos campos de preenchimento do email 
    {
      List<WebElement> elements = driver.findElements(By.id("formBasicEmail"));
      assert(elements.size() > 0);
    }
    // 7 | assertElementPresent | id=formBasicPassword | 
    {
      List<WebElement> elements = driver.findElements(By.id("formBasicPassword"));
      assert(elements.size() > 0);
    }
    // 8 | click | id=formBasicEmail | 
    // preenche os camps com o login invalido 
    driver.findElement(By.id("formBasicEmail")).click();
    // 9 | type | id=formBasicEmail | t@gmail.com
    driver.findElement(By.id("formBasicEmail")).sendKeys("t@gmail.com");
    // 10 | click | id=formBasicPassword | 
    driver.findElement(By.id("formBasicPassword")).click();
    // 11 | type | id=formBasicPassword | 1234
    driver.findElement(By.id("formBasicPassword")).sendKeys("1234");
    // 12 | click | css=.rounded-5 | 
    driver.findElement(By.cssSelector(".rounded-5")).click();
    // 13 | mouseOver | css=.rounded-5 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".rounded-5"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | mouseOut | css=.rounded-5 | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 15 | open | /login | 
    driver.get("http://localhost:5173/login");
  }
}
