// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT001LoginComSucessoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT001LoginComSucesso() {
    // Test name: CT001_LoginComSucesso
    // Step # | name | target | value
    // 1 | open | / | 
    // Acessar o site 
    driver.get("http://localhost:5173/");
    // 2 | click | css=.btn:nth-child(1) | 
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    // 3 | click | id=formBasicEmail | 
    driver.findElement(By.id("formBasicEmail")).click();
    // 4 | type | id=formBasicEmail | aluno@gmail.com
    // login com email valido 
    driver.findElement(By.id("formBasicEmail")).sendKeys("aluno@gmail.com");
    // 5 | type | id=formBasicPassword | 1111
    driver.findElement(By.id("formBasicPassword")).sendKeys("1111");
    // 6 | sendKeys | id=formBasicPassword | ${KEY_ENTER}
    driver.findElement(By.id("formBasicPassword")).sendKeys(Keys.ENTER);
    // 7 | click | css=b | 
    driver.findElement(By.cssSelector("b")).click();
    // 8 | click | css=.navbar-toggler-icon | 
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    // 9 | click | linkText=Categorias | 
    // acrescentar categoria 
    driver.findElement(By.linkText("Categorias")).click();
    // 10 | click | css=.d-flex > .btn | 
    driver.findElement(By.cssSelector(".d-flex > .btn")).click();
    // 11 | click | id=nome | 
    driver.findElement(By.id("nome")).click();
    // 12 | type | id=nome | Teste de categoria 
    driver.findElement(By.id("nome")).sendKeys("Teste de categoria ");
    // 13 | click | css=.btn:nth-child(2) | 
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    // 14 | mouseOver | css=.btn:nth-child(2) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".btn:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 15 | click | css=.d-flex > .btn | 
    driver.findElement(By.cssSelector(".d-flex > .btn")).click();
    // 16 | mouseOver | css=.d-flex > .btn | 
    {
      WebElement element = driver.findElement(By.cssSelector(".d-flex > .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 17 | mouseOut | css=.d-flex > .btn | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 18 | click | id=nome | 
    driver.findElement(By.id("nome")).click();
    // 19 | type | id=nome | Poupar
    driver.findElement(By.id("nome")).sendKeys("Poupar");
    // 20 | click | css=.btn:nth-child(2) | 
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    // 21 | mouseOver | css=.btn:nth-child(2) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".btn:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 22 | click | css=.navbar-toggler | 
    driver.findElement(By.cssSelector(".navbar-toggler")).click();
    // 23 | click | linkText=Transações | 
    // adicionar transaçoes 
    driver.findElement(By.linkText("Transações")).click();
    // 24 | click | css=.mb-3:nth-child(1) | 
    driver.findElement(By.cssSelector(".mb-3:nth-child(1)")).click();
    // 25 | click | id=descricao | 
    driver.findElement(By.id("descricao")).click();
    // 26 | type | id=descricao | caixinha natal
    driver.findElement(By.id("descricao")).sendKeys("caixinha natal");
    // 27 | click | id=data | 
    driver.findElement(By.id("data")).click();
    // 28 | click | id=data | 
    driver.findElement(By.id("data")).click();
    // 29 | type | id=data | 2025-12-25
    driver.findElement(By.id("data")).sendKeys("2025-12-25");
    // 30 | click | id=novaCategoria | 
    driver.findElement(By.id("novaCategoria")).click();
    // 31 | select | id=novaCategoria | label=Poupar
    {
      WebElement dropdown = driver.findElement(By.id("novaCategoria"));
      dropdown.findElement(By.xpath("//option[. = 'Poupar']")).click();
    }
    // 32 | click | css=option:nth-child(5) | 
    driver.findElement(By.cssSelector("option:nth-child(5)")).click();
    // 33 | click | xpath=//input[@id='novaCategoria'] | 
    driver.findElement(By.xpath("//input[@id=\'novaCategoria\']")).click();
    // 34 | type | xpath=//input[@id='novaCategoria'] | 500
    driver.findElement(By.xpath("//input[@id=\'novaCategoria\']")).sendKeys("500");
    // 35 | click | css=.btn:nth-child(4) | 
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
    // 36 | click | id=descricao | 
    driver.findElement(By.id("descricao")).click();
    // 37 | click | id=descricao | 
    driver.findElement(By.id("descricao")).click();
    // 38 | click | id=descricao | 
    driver.findElement(By.id("descricao")).click();
    // 39 | doubleClick | id=descricao | 
    {
      WebElement element = driver.findElement(By.id("descricao"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 40 | click | id=descricao | 
    driver.findElement(By.id("descricao")).click();
    // 41 | click | id=descricao | 
    driver.findElement(By.id("descricao")).click();
    // 42 | type | id=descricao | faxina 
    driver.findElement(By.id("descricao")).sendKeys("faxina ");
    // 43 | click | id=data | 
    driver.findElement(By.id("data")).click();
    // 44 | type | id=data | 2025-12-26
    driver.findElement(By.id("data")).sendKeys("2025-12-26");
    // 45 | click | css=.form-check:nth-child(2) > .form-check-label | 
    driver.findElement(By.cssSelector(".form-check:nth-child(2) > .form-check-label")).click();
    // 46 | click | id=novaCategoria | 
    driver.findElement(By.id("novaCategoria")).click();
    // 47 | select | id=novaCategoria | label=Teste de categoria
    {
      WebElement dropdown = driver.findElement(By.id("novaCategoria"));
      dropdown.findElement(By.xpath("//option[. = 'Teste de categoria']")).click();
    }
    // 48 | click | css=option:nth-child(4) | 
    driver.findElement(By.cssSelector("option:nth-child(4)")).click();
    // 49 | click | xpath=//input[@id='novaCategoria'] | 
    driver.findElement(By.xpath("//input[@id=\'novaCategoria\']")).click();
    // 50 | type | xpath=//input[@id='novaCategoria'] | 200
    driver.findElement(By.xpath("//input[@id=\'novaCategoria\']")).sendKeys("200");
    // 51 | sendKeys | xpath=//input[@id='novaCategoria'] | ${KEY_ENTER}
    driver.findElement(By.xpath("//input[@id=\'novaCategoria\']")).sendKeys(Keys.ENTER);
    // 52 | click | css=.btn:nth-child(4) | 
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
    // 53 | mouseOver | css=.btn:nth-child(4) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".btn:nth-child(4)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 54 | mouseOut | css=.btn:nth-child(4) | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 55 | click | css=tr:nth-child(1) > td > .btn path | 
    driver.findElement(By.cssSelector("tr:nth-child(1) > td > .btn path")).click();
    // 56 | click | css=.table-striped td:nth-child(1) | 
    driver.findElement(By.cssSelector(".table-striped td:nth-child(1)")).click();
    // 57 | click | css=.form-check:nth-child(1) > .form-check-label | 
    driver.findElement(By.cssSelector(".form-check:nth-child(1) > .form-check-label")).click();
    // 58 | click | css=.form-check:nth-child(1) > .form-check-label | 
    driver.findElement(By.cssSelector(".form-check:nth-child(1) > .form-check-label")).click();
    // 59 | click | css=.form-check:nth-child(1) > .form-check-label | 
    driver.findElement(By.cssSelector(".form-check:nth-child(1) > .form-check-label")).click();
    // 60 | click | css=.form-check:nth-child(2) > .form-check-label | 
    driver.findElement(By.cssSelector(".form-check:nth-child(2) > .form-check-label")).click();
    // 61 | click | id=data | 
    driver.findElement(By.id("data")).click();
    // 62 | type | id=data | 2025-12-25
    driver.findElement(By.id("data")).sendKeys("2025-12-25");
    // 63 | click | id=descricao | 
    driver.findElement(By.id("descricao")).click();
    // 64 | click | id=descricao | 
    driver.findElement(By.id("descricao")).click();
    // 65 | doubleClick | id=descricao | 
    {
      WebElement element = driver.findElement(By.id("descricao"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 66 | type | id=descricao | poupar
    driver.findElement(By.id("descricao")).sendKeys("poupar");
    // 67 | click | id=novaCategoria | 
    driver.findElement(By.id("novaCategoria")).click();
    // 68 | select | id=novaCategoria | label=Poupar
    {
      WebElement dropdown = driver.findElement(By.id("novaCategoria"));
      dropdown.findElement(By.xpath("//option[. = 'Poupar']")).click();
    }
    // 69 | click | css=option:nth-child(5) | 
    driver.findElement(By.cssSelector("option:nth-child(5)")).click();
    // 70 | click | id=descricao | 
    driver.findElement(By.id("descricao")).click();
    // 71 | type | id=descricao | caixinha de natal
    driver.findElement(By.id("descricao")).sendKeys("caixinha de natal");
    // 72 | click | xpath=//input[@id='novaCategoria'] | 
    driver.findElement(By.xpath("//input[@id=\'novaCategoria\']")).click();
    // 73 | type | xpath=//input[@id='novaCategoria'] | 500
    driver.findElement(By.xpath("//input[@id=\'novaCategoria\']")).sendKeys("500");
    // 74 | click | css=.btn:nth-child(4) | 
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
    // 75 | mouseOver | css=.btn:nth-child(4) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".btn:nth-child(4)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 76 | mouseOut | css=.btn:nth-child(4) | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 77 | click | css=.btn:nth-child(2) | 
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    // 78 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 79 | click | css=.navbar-toggler | 
    driver.findElement(By.cssSelector(".navbar-toggler")).click();
    // 80 | click | linkText=Dashboard | 
    driver.findElement(By.linkText("Dashboard")).click();
  }
}
