// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT003VisualizarCategoriasTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT003VisualizarCategorias() {
    // Test name: CT003_VisualizarCategorias
    // Step # | name | target | value
    // 1 | open | / | 
    // acessar o site
    driver.get("http://localhost:5173/");
    // 2 | click | css=.navbar-toggler-icon | 
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    // 3 | click | linkText=Categorias | 
    driver.findElement(By.linkText("Categorias")).click();
    // 4 | click | css=.align-items-center:nth-child(3) .btn-warning path | 
    // editando categoria
    driver.findElement(By.cssSelector(".align-items-center:nth-child(3) .btn-warning path")).click();
    // 5 | click | id=nome | 
    driver.findElement(By.id("nome")).click();
    // 6 | click | id=nome | 
    driver.findElement(By.id("nome")).click();
    // 7 | type | id=nome | Edit categoria 
    driver.findElement(By.id("nome")).sendKeys("Edit categoria ");
    // 8 | click | css=.btn:nth-child(2) | 
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    // 9 | click | css=.align-items-center:nth-child(3) .btn-danger path | 
    // exclusão de categoria que esrta relacionada 
    driver.findElement(By.cssSelector(".align-items-center:nth-child(3) .btn-danger path")).click();
    // 10 | click | css=.align-items-center:nth-child(2) .btn-danger | 
    driver.findElement(By.cssSelector(".align-items-center:nth-child(2) .btn-danger")).click();
    // 11 | click | css=.btn-close | 
    driver.findElement(By.cssSelector(".btn-close")).click();
    // 12 | click | css=.align-items-center:nth-child(1) .btn-danger | 
    // exclusão de categoria vazia 
    driver.findElement(By.cssSelector(".align-items-center:nth-child(1) .btn-danger")).click();
    // 13 | click | css=.d-flex > .btn | 
    // criar categoria
    driver.findElement(By.cssSelector(".d-flex > .btn")).click();
    // 14 | click | id=nome | 
    driver.findElement(By.id("nome")).click();
    // 15 | type | id=nome | Teste
    driver.findElement(By.id("nome")).sendKeys("Teste");
    // 16 | click | css=.btn:nth-child(2) | 
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    // 17 | mouseOver | css=.btn:nth-child(2) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".btn:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
