// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT001_LoginComSucesso', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT001_LoginComSucesso', async function() {
    // Test name: CT001_LoginComSucesso
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:5173/")
    // 2 | click | css=.btn:nth-child(1) | 
    await driver.findElement(By.css(".btn:nth-child(1)")).click()
    // 3 | click | id=formBasicEmail | 
    await driver.findElement(By.id("formBasicEmail")).click()
    // 4 | type | id=formBasicEmail | aluno1@gmail.com
    await driver.findElement(By.id("formBasicEmail")).sendKeys("aluno1@gmail.com")
    // 5 | click | id=formBasicPassword | 
    await driver.findElement(By.id("formBasicPassword")).click()
    // 6 | type | id=formBasicPassword | 1111
    await driver.findElement(By.id("formBasicPassword")).sendKeys("1111")
    // 7 | click | css=b | 
    await driver.findElement(By.css("b")).click()
    // 8 | click | css=.align-content-center | 
    await driver.findElement(By.css(".align-content-center")).click()
  })
})
