// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT004_CriandoUsuario', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT004_CriandoUsuario', async function() {
    // Test name: CT004_CriandoUsuario
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:5173/")
    // 2 | click | css=.btn:nth-child(2) | 
    await driver.findElement(By.css(".btn:nth-child(2)")).click()
    // 3 | click | id=formNome | 
    await driver.findElement(By.id("formNome")).click()
    // 4 | type | id=formNome | tiao
    await driver.findElement(By.id("formNome")).sendKeys("tiao")
    // 5 | type | id=formEmail | aluno1@gmail.com
    await driver.findElement(By.id("formEmail")).sendKeys("aluno1@gmail.com")
    // 6 | click | id=formPassword | 
    await driver.findElement(By.id("formPassword")).click()
    // 7 | type | id=formPassword | 1111
    await driver.findElement(By.id("formPassword")).sendKeys("1111")
    // 8 | click | id=formConfirmPassword | 
    await driver.findElement(By.id("formConfirmPassword")).click()
    // 9 | type | id=formConfirmPassword | 1111
    await driver.findElement(By.id("formConfirmPassword")).sendKeys("1111")
    // 10 | click | css=b | 
    await driver.findElement(By.css("b")).click()
  })
})
