// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT003_VisualizarCategorias', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT003_VisualizarCategorias', async function() {
    // Test name: CT003_VisualizarCategorias
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:5173/")
    // 2 | click | css=.navbar-toggler-icon | 
    await driver.findElement(By.css(".navbar-toggler-icon")).click()
    // 3 | click | linkText=Categorias | 
    await driver.findElement(By.linkText("Categorias")).click()
    // 4 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 5 | click | id=nome | 
    await driver.findElement(By.id("nome")).click()
    // 6 | click | id=nome | 
    await driver.findElement(By.id("nome")).click()
    // 7 | type | id=nome | crinado nova categoria
    await driver.findElement(By.id("nome")).sendKeys("crinado nova categoria")
    // 8 | click | css=.btn:nth-child(2) | 
    await driver.findElement(By.css(".btn:nth-child(2)")).click()
    // 9 | click | css=.ms-1 | 
    await driver.findElement(By.css(".ms-1")).click()
    // 10 | click | id=nome | 
    await driver.findElement(By.id("nome")).click()
    // 11 | click | id=nome | 
    await driver.findElement(By.id("nome")).click()
    // 12 | doubleClick | id=nome | 
    {
      const element = await driver.findElement(By.id("nome"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 13 | type | id=nome | editando nova categoria
    await driver.findElement(By.id("nome")).sendKeys("editando nova categoria")
    // 14 | click | css=.btn:nth-child(2) | 
    await driver.findElement(By.css(".btn:nth-child(2)")).click()
    // 15 | click | css=.my-1 > path | 
    await driver.findElement(By.css(".my-1 > path")).click()
    // 16 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 17 | click | id=nome | 
    await driver.findElement(By.id("nome")).click()
    // 18 | type | id=nome | casa
    await driver.findElement(By.id("nome")).sendKeys("casa")
    // 19 | click | css=.btn:nth-child(2) | 
    await driver.findElement(By.css(".btn:nth-child(2)")).click()
    // 20 | click | css=.navbar-toggler-icon | 
    await driver.findElement(By.css(".navbar-toggler-icon")).click()
    // 21 | click | linkText=Transações | 
    await driver.findElement(By.linkText("Transações")).click()
    // 22 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 23 | click | id=descricao | 
    await driver.findElement(By.id("descricao")).click()
    // 24 | type | id=descricao | aluguel
    await driver.findElement(By.id("descricao")).sendKeys("aluguel")
    // 25 | click | id=data | 
    await driver.findElement(By.id("data")).click()
    // 26 | type | id=data | 2025-12-01
    await driver.findElement(By.id("data")).sendKeys("2025-12-01")
    // 27 | mouseDownAt | id=novaCategoria | -150,-514.4166870117188
    {
      const element = await driver.findElement(By.id("novaCategoria"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 28 | mouseMoveAt | id=novaCategoria | -150,-514.4166870117188
    {
      const element = await driver.findElement(By.id("novaCategoria"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 29 | mouseUpAt | id=novaCategoria | -150,-514.4166870117188
    {
      const element = await driver.findElement(By.id("novaCategoria"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 30 | click | id=novaCategoria | 
    await driver.findElement(By.id("novaCategoria")).click()
    // 31 | select | id=novaCategoria | label=casa
    {
      const dropdown = await driver.findElement(By.id("novaCategoria"))
      await dropdown.findElement(By.xpath("//option[. = 'casa']")).click()
    }
    // 32 | click | css=option:nth-child(2) | 
    await driver.findElement(By.css("option:nth-child(2)")).click()
    // 33 | click | xpath=//input[@id='novaCategoria'] | 
    await driver.findElement(By.xpath("//input[@id=\'novaCategoria\']")).click()
    // 34 | type | xpath=//input[@id='novaCategoria'] | 500
    await driver.findElement(By.xpath("//input[@id=\'novaCategoria\']")).sendKeys("500")
    // 35 | click | css=.btn:nth-child(4) | 
    await driver.findElement(By.css(".btn:nth-child(4)")).click()
    // 36 | click | css=.btn:nth-child(2) | 
    await driver.findElement(By.css(".btn:nth-child(2)")).click()
    // 37 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 38 | click | css=.my-1 > path | 
    await driver.findElement(By.css(".my-1 > path")).click()
    // 39 | click | css=.navbar-toggler-icon | 
    await driver.findElement(By.css(".navbar-toggler-icon")).click()
    // 40 | click | linkText=Categorias | 
    await driver.findElement(By.linkText("Categorias")).click()
    // 41 | click | css=.btn-danger | 
    await driver.findElement(By.css(".btn-danger")).click()
    // 42 | click | css=.navbar-toggler | 
    await driver.findElement(By.css(".navbar-toggler")).click()
    // 43 | click | linkText=Dashboard | 
    await driver.findElement(By.linkText("Dashboard")).click()
  })
})
