// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT004CriandoUsuarioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.firefox());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT004CriandoUsuario() {
    // Test name: CT004_CriandoUsuario
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:5173/");
    // 2 | click | css=.btn:nth-child(2) | 
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    // 3 | click | id=formNome | 
    driver.findElement(By.id("formNome")).click();
    // 4 | type | id=formNome | tiao
    driver.findElement(By.id("formNome")).sendKeys("tiao");
    // 5 | type | id=formEmail | aluno1@gmail.com
    driver.findElement(By.id("formEmail")).sendKeys("aluno1@gmail.com");
    // 6 | click | id=formPassword | 
    driver.findElement(By.id("formPassword")).click();
    // 7 | type | id=formPassword | 1111
    driver.findElement(By.id("formPassword")).sendKeys("1111");
    // 8 | click | id=formConfirmPassword | 
    driver.findElement(By.id("formConfirmPassword")).click();
    // 9 | type | id=formConfirmPassword | 1111
    driver.findElement(By.id("formConfirmPassword")).sendKeys("1111");
    // 10 | click | css=b | 
    driver.findElement(By.cssSelector("b")).click();
  }
}
