// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT002_LoginInválido', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT002_LoginInválido', async function() {
    // Test name: CT002_LoginInválido
    // Step # | name | target | value
    // 1 | open | / | 
    // Acessa o Site
    await driver.get("http://localhost:5173/")
    // 2 | assertElementPresent | css=b | 
    // Validação dos elementos da tela inicial
    {
      const elements = await driver.findElements(By.css("b"))
      assert(elements.length)
    }
    // 3 | assertElementPresent | css=.btn:nth-child(1) | 
    {
      const elements = await driver.findElements(By.css(".btn:nth-child(1)"))
      assert(elements.length)
    }
    // 4 | assertElementPresent | css=.btn:nth-child(2) | 
    {
      const elements = await driver.findElements(By.css(".btn:nth-child(2)"))
      assert(elements.length)
    }
    // 5 | click | css=.btn:nth-child(1) | 
    await driver.findElement(By.css(".btn:nth-child(1)")).click()
    // 6 | assertElementPresent | id=formBasicEmail | 
    // validação dos campos de preenchimento do email 
    {
      const elements = await driver.findElements(By.id("formBasicEmail"))
      assert(elements.length)
    }
    // 7 | assertElementPresent | id=formBasicPassword | 
    {
      const elements = await driver.findElements(By.id("formBasicPassword"))
      assert(elements.length)
    }
    // 8 | click | id=formBasicEmail | 
    // preenche os camps com o login invalido 
    await driver.findElement(By.id("formBasicEmail")).click()
    // 9 | type | id=formBasicEmail | t@gmail.com
    await driver.findElement(By.id("formBasicEmail")).sendKeys("t@gmail.com")
    // 10 | click | id=formBasicPassword | 
    await driver.findElement(By.id("formBasicPassword")).click()
    // 11 | type | id=formBasicPassword | 1234
    await driver.findElement(By.id("formBasicPassword")).sendKeys("1234")
    // 12 | click | css=.rounded-5 | 
    await driver.findElement(By.css(".rounded-5")).click()
    // 13 | mouseOver | css=.rounded-5 | 
    {
      const element = await driver.findElement(By.css(".rounded-5"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 14 | mouseOut | css=.rounded-5 | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 15 | open | /login | 
    await driver.get("http://localhost:5173/login")
  })
})
